# Nom de l'application
spring.application.name=API-Gateway

# Port de l'API Gateway
server.port=9091

spring.jpa.hibernate.ddl-auto=update

# Augmenter les timeouts
spring.cloud.gateway.httpclient.connect-timeout=10000
spring.cloud.gateway.httpclient.response-timeout=30s

# Configuration Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

logging.level.org.springframework.web.cors=TRACE

# Service discovery configuration
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Mode reactif
spring.main.web-application-type=reactive
logging.level.reactor.netty.http.client=DEBUG

# Logging configuration
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web.reactive=DEBUG
server.address=0.0.0.0

# Configuration du load balancer
spring.cloud.loadbalancer.ribbon.enabled=false
spring.cloud.loadbalancer.enabled=true

# Logging
logging.level.reactor.netty=INFO