spring.application.name=Authentification
# Configuration du port du microservice
server.port=8080
#Enregistrement dans Eureka
eureka.client.register-with-eureka=true

# Configuration des transactions
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
# Logging detaille
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
eureka.instance.prefer-ip-address=true
# Localisation du fichier Firebase
#firebase.config.path=/app/firebase-service-account.json
# Configuration de la connexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/authentification
spring.datasource.username=postgres
spring.datasource.password=zineb123
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuration JPA/Hibernate
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
logging.level.root=INFO
logging.level.com.votrepackage=DEBUG
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.example.authentification=DEBUG
spring.jpa.open-in-view=false
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000







