version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zineb123
      POSTGRES_DB: defaultdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # scripts SQL pour créer toutes les bases



  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  api-gateway:
    build: ./API Gateway
    container_name: api-gateway
    ports:
      - "9091:9091"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
    depends_on:
      - eureka

  eureka:
    build: ./eurekaserver
    container_name: eureka
    ports:
      - "8761:8761"

  authentification:
    build:
      context: ./Authentification
      dockerfile: Dockerfile
    container_name: authentification
    ports:
      - "8080:8080"
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/authentification
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=zineb123
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - FIREBASE_CONFIG_PATH=/app/firebase-service-account.json
    depends_on:
      - postgres
      - eureka



  boutique-service:
    build: ./Boutique-Catalogue-Produits
    container_name: boutique-service
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/boutiqueproduit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=zineb123
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - MINIO_ENDPOINT=http://minio:9000
      - REDIS_HOST=redis
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - postgres
      - eureka
      - minio
      - redis
      - rabbitmq

  cart-service:
    build: ./Cart Service
    container_name: cart-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cartservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=zineb123
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - postgres
      - rabbitmq
      - eureka

  gestion-stocks:
    build: ./Gestion-Stocks
    container_name: gestion-stocks
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/stock
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=zineb123
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - postgres
      - rabbitmq
      - eureka
  ai-service:
    build: ./ai-microservice
    container_name: ai-service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - minio
    environment:
      DATABASE_URL: postgresql://postgres:zineb123@postgres:5432/boutiqueproduit
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET_NAME: boutique-images
      MINIO_PUBLIC_URL: http://minio:9000
      MINIO_SECURE: "false"

  mobile-frontend:
    build:
      context: ./here_mobile
    container_name: mobile-frontend
    env_file: .env            # contient NGROK_AUTHTOKEN=xxxxxxxx
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      CI: "false"
    stdin_open: true          # pour voir le QR Code en temps réel
    tty: true
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
      - "19006:19006"         # (optionnel) DevTools
    depends_on:
      - api-gateway







volumes:
  pgdata:
  minio_data:

